---
- name: extra vars vault
  connection: local
  hosts: localhost
  gather_facts: no

  vars_files:
    - vars/oscreds.yml

  tasks:
    - name: print out encrypted vars
      ansible.builtin.debug:
        msg: "{{ imscloud }}"
      no_log: true
