---
- name: a playbook showing the file module
  hosts: planetexpress
  connection: ansible.builtin.ssh
  gather_facts: no

  vars:
    st: absent

  tasks:

    - name: create a directory where the space station document will reside
      become_user: root
      become: true
      ansible.builtin.file:
        path: "/home/{{ item }}/station_docs"
        state: "{{ st }}"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: "0755"
      loop: [fry, bender, zoidberg]
