---
- name: Getting files 
  hosts: planetexpress
  connection: ansible.builtin.ssh
  gather_facts: no

  tasks:

    - name: Download virus protection severes to install on hosts
      ansible.builtin.get_url:
        url: http://www.clamav.net/downloads/production/clamav-0.99.3.tar.gz
        dest: ~/clamav.tar.gz
