---
- name: a playbook showing the file module
  hosts: planetexpress
  connection: ansible.builtin.ssh
  gather_facts: yes


  tasks:

    - name: create a directory where the space station document will reside
      become_user: root
      become: true
      ansible.builtin.file:
        path: "/home/{{ fileuser }}/station_docs"
        state: directory
        owner: "{{ fileuser }}"
        group: "{{ fileuser }}"
        mode: "0755"

    - name: copy content into a file wiht the year-mo-day
      ansible.builtin.copy:
        content: "Earth\nMars\nSaturn\nEuropa\n"
        dest: "/home/{{ fileuser }}/station_docs/navdata-{{ansible_date_time.date}}.txt"
