---
- name: a playbook showing the file module
  hosts: planetexpress
  connection: ansible.builtin.ssh
  gather_facts: no


  tasks:

    - name: create a directory where the space station document will reside
      become_user: root
      become: true
      ansible.builtin.file:
        path: "/home/{{ fileuser }}/station_docs"
        state: directory
        owner: "{{ fileuser }}"
        group: "{{ fileuser }}"
        mode: "0755"
