---
- name: Playbook - Install figlet # metadata
  hosts: planetexpress:!farnsworth # Take planetexpressgroup and remove farnsworth
  connection: ssh  #default is connection plugin ssh.py
  gather_facts: yes #default is yes

  tasks: #a list of what we want to do
  - name: using apt to install figlet #metadata
    ansible.builtin.apt: #module we want to run apt.py
      name: figlet #param
      state: present #param to module
    become: yes # elevate status to admin, sudo, enable, etc.

