---
- name: bootstrapping and new user
  hosts: raiders
  connection: ansible.builtin.ssh
  gather_facts: False

  vars_files:
    - vars/newusers1.yml


  tasks:
    
    #update the apt catalog
    - name: "ensure apt is updated"
      ansible.builtin.raw:  "apt update -y"
      become: yes


    # install Python with ansible
    # the raw module will ALWAYS issue your command
    # no idempotence here!
    # therefore, use it sparingly!!
    - name: "bootstrap python install"
      ansible.builtin.raw: "apt install -y python3-pip"
      become: yes


    #create new group
    - name: create the new group sandbox
      ansible.builtin.group:
        name: sandbox
        state: present
      become: yes


    #create new user on target system
    - name: Add user 'exampleuser with group of 'sandbox'
      ansible.builtin.user: 
        name: "{{ item }}"
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        group: sandbox
      become: yes
      loop: "{{ users1 }}"     
