---
- name: apache server install
  hosts: web
  gather_facts: false
  become: yes

  tasks:

    - name: latest apache version installed
      ansible.builtin.package:
        name: 
          - apache2
          - mariadb-server
          - mariadb-client
        state: latest
      notify:
        - restart_webservices

    - name: Apache enabled and running
      ansible.builtin.service:
        name: apache2
        enabled: yes
        state: started

    - name: copy index.html
      ansible.builtin.copy:
        src: ~/mycode/files/index.html
        dest: /var/www/html/

    - name: download a copy of apache2
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/rzfeeser/alta3files/master/apache2.conf
        dest: /etc/apache2
      notify:
        - restart_apache

    - name: mysql (mariadb) is running
      ansible.builtin.service:
        name: mariadb
        enabled: yes
        state: started

    - name: modify sql conf file to listen on all interfaces
      ansible.builtin.lineinfile:
        path: /etc/mysql/my.cnf
        regex: "^bind-address"
        line: "bind-address=1.1.1.1"
      notify: 
        - restart_mysql

  handlers:
     - name: restart_apache #will only run if task above ran (got changed)
       ansible.builtin.service:
         name: apache2
         state: restarted
       listen: restart_webservices


     - name: restart_mysql
       ansible.builtin.service:
         name: mariadb
         state: restarted
       listen: restart_webservices
