---
- name: playtook with the register keyword
  hosts: planetexpress
  gather_facts: false
  connection: ansible.builtin.ssh

  tasks:
    - name: issue a trivial command
      ansible.builtin.command: ls /lib/
      register: slappy

    - name: debug - display data returned
      ansible.builtin.debug:
        var: slappy

    - name: print stderror
      ansible.builtin.debug:
        var: slappy.stderr
