---
- name: bootstrapping and new user
  hosts: raiders
  connection: ssh
  gather_facts: False

  tasks:

    #Remove the user
    - name: remove a user
      ansible.builtin.user:
        name: exampleuser
        state: absent
        remove: yes
      become: yes

    #Remove the group 'sandbox;
    - name: remove group sandbox
      ansible.builtin.group:
         name: sandbox
         state: absent
      become: yes 
