---
- name: get-url doenload the protected file
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Access the website if URL is live
      ansible.builtin.uri:
        method: GET
        url: http://10.10.2.4/admin/secure.txt
        status_code: 401
        return_content: true
      register: validateurl

    - name: INFO HTTP Response for the URL
      ansible.builtin.debug:
        var: validateurl.msg

    - name: Acess again with Basic authentication and download the file
      ansible.builtin.uri:
        method: GET
        url:  http://10.10.2.4/admin/secure.txt
        url_username: sammy
        url_password: larry
        return_content: true
        status_code: 200
      register: validateurl2

    - name: show the content was retrieved
      ansible.builtin.debug:
        var: validateurl2

    - name: put the content into a file
      ansible.builtin.copy:
        content: "{{ validateurl2.content }}"
        dest: ~/mycode/secret-file-fry.txt
